services:
  api:
    build: .
    container_name: los-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/los_api
    ports:
      - "8000:8000"

  db:
    image: postgres:16-alpine
    container_name: los-postgres
    environment:
      POSTGRES_DB: los_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d los_api"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: